### ISSUE TITLE
I am running the workshop of serverlesspresso and I am getting this error

### ISSUE THREAD

**Issue by marorvel31** [aws-samples/serverless-coffee-workshop#52] opened 2024-02-14 00:00 UTC
Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 10b9bca8-1a3b-4782-bbdf-0be6def68c44)" (RequestToken: 428f38f8-1971-aec1-d05e-81d773623783, HandlerErrorCode: InvalidRequest)

**Comment by kimberlyamandalu** [comment] 2024-02-14 21:00
I am also getting this error today. I updated the runtime in the cfn templates to `nodejs20.x` but sam will not pick up the new version and keeps using 14 for some reason...

**Comment by bfreiberg** [comment] 2024-02-27 09:43
Hi @kimberlyamandalu, thanks for your bug report. The issue can be resolved for now by updating the runtime version of the Lambda functions to Node v16. An upgrade to Node v20 isn't as easy, as that version uses the AWS SDK v3 instead of v2.

We are currently working on updating the functions to resolve this.

**Comment by bfreiberg** [comment] 2024-02-27 09:44
Duplicate of #53

**Comment by bfreiberg** [comment] 2024-04-21 15:14
Hi, the template has been updated and it should work again. Could you please test it again

**Closed** 2024-06-12 10:45 UTC
